version: "3.1"
services:
  db:
    image: "postgres:13"
    restart: always
    ports:
      - "1212:5432"
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:
